steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/tercera-juventud-django/tercera-juventud-django', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/tercera-juventud-django/tercera-juventud-django:latest']

options:
  logging: CLOUD_LOGGING_ONLY